# Generated by Django 6.0.1 on 2026-01-14 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_safe', models.BooleanField(help_text='Is the user currently safe?')),
                ('notes', models.TextField(blank=True, help_text='Additional notes from follow-up check-in', null=True)),
                ('needs_support', models.BooleanField(default=False, help_text='Does user need additional support or resources?')),
                ('support_type', models.CharField(blank=True, help_text='Type of additional support needed (if any)', max_length=100, null=True)),
                ('followup_time', models.DateTimeField(auto_now_add=True)),
                ('sos', models.ForeignKey(help_text='The SOS request this follow-up is for', on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='sos.sosrequest')),
            ],
            options={
                'verbose_name': 'Follow-Up Check-in',
                'verbose_name_plural': 'Follow-Up Check-ins',
                'ordering': ['-followup_time'],
            },
        ),
        migrations.CreateModel(
            name='IncidentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1-5 (1=poor, 5=excellent)')),
                ('comment', models.TextField(blank=True, help_text='Optional feedback comment', null=True)),
                ('was_helpful', models.BooleanField(default=True, help_text='Did the response help resolve the emergency?')),
                ('would_recommend', models.BooleanField(default=True, help_text='Would user recommend LifeLink to others?')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('sos', models.OneToOneField(help_text='The SOS request this feedback is for', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='sos.sosrequest')),
            ],
            options={
                'verbose_name': 'Incident Feedback',
                'verbose_name_plural': 'Incident Feedback',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
