# Generated by Django 6.0.1 on 2026-01-14 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supabase_user_id', models.CharField(help_text='UUID from Supabase Auth', max_length=255, unique=True)),
                ('role', models.CharField(choices=[('user', 'Regular User'), ('responder', 'Emergency Responder')], default='user', help_text='User role in the system', max_length=20)),
                ('trust_score', models.IntegerField(default=50, help_text='Trust score from 0-100, affects SOS prioritization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResponderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.JSONField(default=list, help_text='List of responder skills/certifications')),
                ('is_available', models.BooleanField(default=True, help_text='Whether responder is currently available for assignments')),
                ('reputation_score', models.IntegerField(default=50, help_text='Reputation score from 0-100, based on response history')),
                ('last_known_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_known_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Base user profile for this responder', on_delete=django.db.models.deletion.CASCADE, related_name='responder_profile', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Responder Profile',
                'verbose_name_plural': 'Responder Profiles',
                'ordering': ['-reputation_score'],
            },
        ),
    ]
