# Generated by Django 6.0.1 on 2026-01-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_email_userprofile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contacts',
            field=models.JSONField(blank=True, default=list, help_text='List of emergency contacts (max 3)'),
        ),
    ]
