# Generated by Django 6.0.1 on 2026-01-14 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('sos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_type', models.CharField(choices=[('police', 'Police'), ('fire', 'Fire Department'), ('medical', 'Medical/Ambulance'), ('other', 'Other Authority')], help_text='Type of authority escalated to', max_length=20)),
                ('reason', models.TextField(help_text='Reason for escalating to authorities')),
                ('escalated_at', models.DateTimeField(auto_now_add=True)),
                ('authority_reference', models.CharField(blank=True, help_text='Reference ID from the authority (mock for MVP)', max_length=100, null=True)),
                ('sos', models.ForeignKey(help_text='The SOS request that was escalated', on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='sos.sosrequest')),
            ],
            options={
                'verbose_name': 'Authority Escalation',
                'verbose_name_plural': 'Authority Escalations',
                'ordering': ['-escalated_at'],
            },
        ),
        migrations.CreateModel(
            name='ResponderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted by Responder'), ('en_route', 'En Route'), ('on_scene', 'On Scene'), ('completed', 'Completed'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='assigned', help_text='Current status of this assignment', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('responder_notes', models.TextField(blank=True, help_text='Notes from responder about the response', null=True)),
                ('responder', models.ForeignKey(help_text='The responder assigned to this SOS', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.responderprofile')),
                ('sos', models.ForeignKey(help_text='The SOS request this assignment is for', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='sos.sosrequest')),
            ],
            options={
                'verbose_name': 'Responder Assignment',
                'verbose_name_plural': 'Responder Assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('sos', 'responder')},
            },
        ),
    ]
