# Generated by Django 6.0.1 on 2026-01-14 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude of emergency location', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude of emergency location', max_digits=9)),
                ('location_description', models.TextField(blank=True, help_text='Text description of location if GPS is unavailable', null=True)),
                ('silent_mode', models.BooleanField(default=False, help_text='True if user activated SOS silently (cannot speak)')),
                ('description', models.TextField(blank=True, help_text='Optional emergency description or keywords', null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('analyzing', 'Analyzing'), ('assigned', 'Assigned to Responder'), ('in_progress', 'Response In Progress'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='created', help_text='Current lifecycle status of the SOS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Timestamp when SOS was resolved', null=True)),
                ('user', models.ForeignKey(help_text='User who created this SOS request', on_delete=django.db.models.deletion.CASCADE, related_name='sos_requests', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'SOS Request',
                'verbose_name_plural': 'SOS Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
