# Generated by Django 6.0.1 on 2026-01-14 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Unique code like 'heart_attack', 'road_accident'", max_length=50, unique=True)),
                ('name', models.CharField(help_text="Display name like 'Heart Attack', 'Road Accident'", max_length=100)),
                ('icon', models.CharField(help_text='Emoji icon for the card, e.g., 🫀, 🚗', max_length=10)),
                ('category', models.CharField(choices=[('medical', 'Medical Emergency'), ('safety', 'Safety/Security'), ('accident', 'Accident'), ('emotional', 'Emotional/Mental Health')], help_text='Emergency category for routing', max_length=20)),
                ('urgency_boost', models.IntegerField(default=20, help_text='Points added to base urgency score (0-50)')),
                ('keywords', models.JSONField(default=list, help_text='Keywords associated with this emergency type')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which cards appear (lower = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this card is shown to users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Emergency Card',
                'verbose_name_plural': 'Emergency Cards',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='sosrequest',
            name='additional_details',
            field=models.TextField(blank=True, help_text='Additional context not covered by the selected card', null=True),
        ),
        migrations.AddField(
            model_name='sosrequest',
            name='estimated_victims',
            field=models.IntegerField(default=1, help_text='Estimated number of people needing help'),
        ),
        migrations.AddField(
            model_name='sosrequest',
            name='is_bystander_report',
            field=models.BooleanField(default=False, help_text='True if reporter is a bystander reporting for someone else'),
        ),
        migrations.AddField(
            model_name='sosrequest',
            name='victim_condition',
            field=models.CharField(blank=True, choices=[('conscious', 'Conscious and responsive'), ('semi_conscious', 'Semi-conscious / Confused'), ('unconscious', 'Unconscious / Unresponsive'), ('unknown', 'Unknown / Cannot determine')], default='unknown', help_text="Victim's apparent condition (for bystander reports)", max_length=20),
        ),
        migrations.AddField(
            model_name='sosrequest',
            name='selected_card',
            field=models.ForeignKey(blank=True, help_text='Emergency card selected by user (quick-tap)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_requests', to='sos.emergencycard'),
        ),
    ]
